### ISSUE TITLE
Changed Signature: CCSGameRules_ctor

### ISSUE THREAD

**Issue by busheezy** [zer0k-z/cs2kz_metamod#15]
I'm sure you already know but I figured I'd make an issue before people get confused to why things aren't working.

It looks like CCSGameRules_ctor has changed a bit. I'm running linux.

Thanks for everything

**Comment by zer0k-z** [comment]
Yeah, I'm not on my pc yet to fix the signature or to make an issue for this as a PSA either, thanks for the post :D

**Comment by zer0k-z** [comment]
Fixed with https://github.com/zer0k-z/cs2kz_metamod/commit/95bb42edb9eb122a42d49a48753b60edc7e87734
